apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app  # Replace with your app name
spec:
  replicas: 2  # Number of replicas (adjust as needed)
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: openphoenixdh/phoenixapptest1 # Replace with your image details
        ports:
        - containerPort: 5000  # Adjust port if needed (default Flask port)
